### PR TITLE
Concatenate the output (stdout+stderr) of *every* step

### PR DESCRIPTION
**Pull request by flipreverse**

### CODE REVIEW

**Comment by nalgeon** [comment]
To be honest, I prefer the current behavior.

**Comment by flipreverse** [comment]
> To be honest, I prefer the current behavior.

What about an additional config switch?

**Comment by nalgeon** [comment]
I'd rather not add this config switch, sorry. I don't currently see enough compelling reasons to complicate this behavior.

**Comment by Zxilly** [comment]
A main reason is to get errors reported by the compiler.

**Comment by flipreverse** [comment]
> A main reason is to get errors reported by the compiler.

Exactly. All warnings occuring in the first step (compiling) will be discarded if the program os executed in the second step.

**Pull request closed without merging**
